server:
  port: 8000
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlinAuth
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true


