server:
  port: 8000
  servlet:
    context-path: "/api"

spring:
  application:
    name: kotlin_auth

  datasource:
    url: jdbc:postgresql://db:5432/kotlin_auth
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-and-jpa-kfd
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/kotlinAuth
            user-name-attribute: preferred_username


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
